// Chapter 2 — The device page.
export default {
  id: "ch02",
  number: 2,
  title: "The device page",
  intro: "Chapter two. The device page. Everything about one unit, in one place.",
  theme: "light",
  login: true,
  steps: [
    { id: "open", text: "Open a device from the fleet list or the search box. The header shows its nickname, serial, venue, build and whether it is online right now.",
      run: async (s) => { await s.page.goto(s.BASE + "/devices/" + s.HERO, { waitUntil: "load" }); await s.zoom(); await s.hold(800); await s.glide(".dd-head, h1, .ddc-title", { dur: 1000 }).catch(() => {}); } },
    { id: "vitals", text: "Vitals is the battery chart. Switch the window with the range buttons. The colour of the line tells you whether the unit was on its charging pad.",
      run: async (s) => { await s.click("button:has-text('24h')").catch(() => {}); await s.hold(1500); await s.glide("#batteryChart", { dur: 900 }).catch(() => {}); } },
    { id: "temp", text: "Temp and RAM are the other two vitals. A tablet that lives next to the grill shows up here long before it fails.",
      run: async (s) => { await s.click("button:has-text('Temp')").catch(() => {}); await s.hold(1800); await s.click("button:has-text('RAM')").catch(() => {}); await s.hold(1200); } },
    { id: "placement", text: "Placement says which restaurant and group the device belongs to. Change it here when a unit moves between venues.",
      run: async (s) => { await s.glide("text=Placement >> nth=0", { dur: 900 }).catch(() => {}); await s.hold(600); await s.glide("text=Restaurant >> nth=0", { dur: 700 }).catch(() => {}); } },
    { id: "nickname", text: "Give it a name people use on the floor. Names show up everywhere the serial does, and restaurant owners only ever see the name.",
      run: async (s) => { await s.click(".dd-nick summary").catch(() => {}); await s.hold(600); await s.glide(".dd-nick input[name=nickname]", { dur: 600 }).catch(() => {}); await s.hold(900); await s.page.keyboard.press("Escape"); } },
    { id: "apps", text: "Applications lists what is installed, with versions. Our own apps first, system apps folded away.",
      run: async (s) => { await s.click("#dd-tab-apps"); await s.hold(1200); await s.scroll(250, 800); await s.hold(600); } },
    { id: "history", text: "History is the timeline: reboots, build changes, crashes, actions we sent. When something looks odd, start here.",
      run: async (s) => { await s.click("#dd-tab-history"); await s.hold(1500); await s.scroll(200, 700); } },
    { id: "alerts", text: "Alerts shows what fired for this device and what is still open. Acknowledging here is the same as on the Alerts page.",
      run: async (s) => { await s.click("#dd-tab-alerts"); await s.hold(1500); } },
    { id: "notes", text: "Notes are free text for the team: a cracked screen, a unit reserved for testing. They stay with the device.",
      run: async (s) => { await s.click("#dd-tab-summary").catch(() => {}); await s.hold(500); await s.glide("textarea[name=notes]", { dur: 900 }).catch(() => {}); } },
    { id: "actions", text: "The buttons at the top act on this device only: remote control, reboot, kiosk, and the full action list under Actions.",
      run: async (s) => { await s.scroll(-1200, 700); await s.glide("a:has-text('Remote Control')", { dur: 900 }).catch(() => {}); await s.hold(500); await s.glide("text=Actions >> nth=0", { dur: 700 }).catch(() => {}); } },
  ],
};
